### ISSUE TITLE
Error when linting with Angular 4.0.2

### ISSUE THREAD

**Issue by tsvetomir** [mgechev/codelyzer#294]
This used to work fine with Angular 4.0.1

### Repro steps.
```
ng new lint-test
cd lint-test
npm install --save-dev codelyzer@3.0.0-beta.4
ng lint --type-check
```

### The log given by the failure.
```
TypeError: this.symbolResolver.getSymbolByModule is not a function
    at StaticReflector.findDeclaration (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:22794:63)
    at StaticReflector.initializeConversionMap (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:23012:36)
    at new StaticReflector (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:22741:14)
    at ContextSymbols.init (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2479:26)
    at new ContextSymbols (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2340:14)
    at ProjectSymbols.getRootContext (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2558:28)
    at ProjectSymbols.getLazyLoadedContexts (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2573:18)
    at Object.exports.parseTemplate (/tmp/angular402/node_modules/codelyzer/angular/templates/contextAwareTemplateParser.js:21:35)
    at Ng2Walker.visitNg2Component (/tmp/angular402/node_modules/codelyzer/angular/ng2Walker.js:119:64)
    at Ng2Walker.visitClassDeclaration (/tmp/angular402/node_modules/codelyzer/angular/ng2Walker.js:50:18)
[... snip ...]
All files pass linting.
```

**Comment by mgechev** [comment]
Yes, it's better to switch to 2.1.1 (and 3.0.0 starting from Monday next week).

3.0.0 right now is in beta so it's not really intended for production usage.
