### ISSUE TITLE
vscode-tslint: 'Cannot find module 'tslint/lib/lint''

### ISSUE THREAD

**Issue by mlc-mlapis** [mgechev/codelyzer#165]
Configuration:
```
"codelyzer": "1.0.0-beta.4",
"tslint": "4.0.2",
"typescript": "2.0.10",
"@angular/core": "2.2.3",
```

VS Code: 1.7.2

at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
**at Object.<anonymous> (...\node_modules\codelyzer\selectorNameBase.js:8:12)**
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)

**Comment by mgechev** [comment]
It's duplication of https://github.com/mgechev/codelyzer/issues/162.

By the end of the week I'll release version which works with tslint 4.0.0. In order to stop getting this error try: `rm -rf node_modules/tslint && npm i tslint@^3.0.0`.

**Comment by mlc-mlapis** [comment]
Minko, tkank you.

**Comment by mgechev** [comment]
Sure, let me know if you have any other problems.

**Comment by mgechev** [comment]
You can now use `2.0.0-beta.1` which works with tslint 4.

**Comment by mlc-mlapis** [comment]
Great, I will test it.

**Comment by SatishMHiremath** [comment]
0
down vote
Codelyzer

A set of tslint rules for static code analysis of Angular TypeScript projects.

You can run the static code analyzer over web apps, NativeScript, Ionic, etc.

Angular CLI Angular CLI has support for codelyzer.Run the below npm command for tslint

npm i tslint-angular
